spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:~/library-batch-chunk;DB_CLOSE_ON_EXIT=FALSE
    username: fiap
    password: fiap
    driverClassName: org.h2.Driver

file:
  input: classpath:alunosfile.txt
